version: '3'
services:
  dremio:
    image: dremio/dremio-oss:24.0.0
    container_name: dremio
    ports:
      - "9047:9047"
      - "31010:31010"
    volumes:
      - ./dremio-data:/var/lib/dremio
      - ./parquet-files:/parquet-files
    networks:
      - local_david
networks:
  local_david:
    external: true